service: library
runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.95
  min_instances: 1
  max_instances: 1

# Environment variables
includes:
  - env.yaml

# Basic handlers
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# Minimize resource usage
inbound_services:
  - warmup
  
# By default app engine will run npm start if entrypoint not defined
# entrypoint: npm start
